### ISSUE TITLE
Remove ui-loader border with border-width=0

### ISSUE THREAD

**Issue by DzenisevichK** [jquery/jquery-mobile#7288]
Currently in jquery.mobile.structure (1.4.2 version) we have:
```css
.ui-loader {
	display: none;
	z-index: 9999999;
	position: fixed;
	top: 50%;
	left: 50%;
	border:0;
}
```

More flexible is to remove border with `border-width: 0` so it will be easy to restore it with just `border-width: 1px` in other case we need additionally define `border-style` and `border-color` (and this already theming).
