### ISSUE TITLE
Checkbox without text is displayed incorrectly

### ISSUE THREAD

**Issue by slavap** [jquery/jquery-mobile#8314]
Test case: http://jsbin.com/jeloxizaye/edit?html,css,output

data-iconpos="notext" not working at all and leads to broken checkbox.

UPDATE: just for the record, the same problem with radio as well, so .ui-radio should be added to fix.

FIX:
```css
.ui-checkbox .ui-btn:empty, .ui-radio .ui-btn:empty {
  min-height: 1em;
  padding-right: 0;
}
```
